openapi: 3.0.0
info:
  title: Media Processor API
  version: 1.0.0
  description: API for processing media files including upload and OCR

servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /upload:
    post:
      summary: Upload single file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful upload
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string

  /upload/batch:
    post:
      summary: Upload multiple files
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                images:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        '200':
          description: Successful batch upload
          content:
            application/json:
              schema:
                type: object
                properties:
                  urls:
                    type: array
                    items:
                      type: string
                  errors:
                    type: object
                    additionalProperties:
                      type: string

  /ocr:
    post:
      summary: Perform OCR on image
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: URL of the image to process
      responses:
        '200':
          description: Successful OCR
          content:
            application/json:
              schema:
                type: object
